import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import { AuthProvider } from "../Context/AuthContext";
import { TaskProvider } from "@/Context/TaskContex";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <TaskProvider>
      <AuthProvider>
        <html lang="en">
          <body className={inter.className}>
            <Navbar />
            {children}
          </body>
        </html>
      </AuthProvider>
    </TaskProvider>
  );
}
